spring.application.name=activityService
#mongodb://localhost:27017/

spring.data.mongodb.uri=mongodb://localhost:27017/fitnessactivity
spring.data.mongodb.database=fitnessactivity

# Server configuration
server.port=8082