spring.application.name=activity-service
#mongodb://localhost:27017/
spring.mongodb.uri=mongodb://localhost:27017/fitnessactivity
spring.mongodb.database=fitnessactivity
# Server configuration
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#RabbitMQ
rabbitmq.exchange.name=fitness.exchange
rabbitmq.exchange.queue=activity.queue
rabbitmq.exchange.routing=activity.tracking
