spring.application.name=api-gateway
server.port=8080
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Gateway Route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].predicates[1]=Path=/api/users
#logging.level.org.springframework.cloud.gateway=TRACE
#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.enabled=true