#spring.application.name=api-gateway
server.port=8080
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ========================
# Gateway Routes
# ========================
# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/users/(?<segment>.*), /${segment}
# AI SERVICE
spring.cloud.gateway.routes[1].id=ai-service
spring.cloud.gateway.routes[1].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/recommendation/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/recommendation/(?<segment>.*), /recommendation/${segment}
# ACTIVITY SERVICE
spring.cloud.gateway.routes[2].id=activity-service
spring.cloud.gateway.routes[2].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/activities/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/activities/(?<segment>.*), /${segment}
# ========================
# Swagger Aggregation
# ========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/api/users/v3/api-docs
springdoc.swagger-ui.urls[1].name=AI Service
springdoc.swagger-ui.urls[1].url=/api/recommendation/v3/api-docs
springdoc.swagger-ui.urls[2].name=Activity Service
springdoc.swagger-ui.urls[2].url=/api/activities/v3/api-docs
# ========================
# Actuator + Debug
# ========================
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
logging.level.org.springframework.cloud.gateway=TRACE
# CORS Configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:8080
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
# IMPORTANT for preflight (OPTIONS)
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true